// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6u758RD6IXjUfWaCIIJHSywZKxgEy7TM',
    appId: '1:698737973836:web:1f65c9a3daf49d36a172e9',
    messagingSenderId: '698737973836',
    projectId: 'summerclass2026-1-d6d76',
    authDomain: 'summerclass2026-1-d6d76.firebaseapp.com',
    storageBucket: 'summerclass2026-1-d6d76.firebasestorage.app',
    measurementId: 'G-D7K17K940Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc0i2snIgYiTcEznJtG2XUYWntT0-Y814',
    appId: '1:698737973836:android:93ceeda103aca7a4a172e9',
    messagingSenderId: '698737973836',
    projectId: 'summerclass2026-1-d6d76',
    storageBucket: 'summerclass2026-1-d6d76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz5Jca-bpU9994_VGZDnpX87eQqw28Cbg',
    appId: '1:698737973836:ios:cfa755c59194690ca172e9',
    messagingSenderId: '698737973836',
    projectId: 'summerclass2026-1-d6d76',
    storageBucket: 'summerclass2026-1-d6d76.firebasestorage.app',
    iosBundleId: 'com.example.bibliotecaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz5Jca-bpU9994_VGZDnpX87eQqw28Cbg',
    appId: '1:698737973836:ios:cfa755c59194690ca172e9',
    messagingSenderId: '698737973836',
    projectId: 'summerclass2026-1-d6d76',
    storageBucket: 'summerclass2026-1-d6d76.firebasestorage.app',
    iosBundleId: 'com.example.bibliotecaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6u758RD6IXjUfWaCIIJHSywZKxgEy7TM',
    appId: '1:698737973836:web:2d9b5d47ebf321a4a172e9',
    messagingSenderId: '698737973836',
    projectId: 'summerclass2026-1-d6d76',
    authDomain: 'summerclass2026-1-d6d76.firebaseapp.com',
    storageBucket: 'summerclass2026-1-d6d76.firebasestorage.app',
    measurementId: 'G-BSXM7SWC8C',
  );
}
